// SPDX-FileCopyrightText: 2026 missing-foss
// SPDX-License-Identifier: GPL-3.0-or-later
using Toybox.Application.Storage;
using Toybox.Application.Properties;
using Toybox.Lang;

// Shared helpers for the (:test) suites.
//
// The annotation goes on the MODULE and deliberately not on the functions
// inside it. Both forms keep the code out of a release build (monkeyc only
// compiles (:test) code under -t), but the test runner collects every
// annotated *function* as a test case — annotating these individually made
// the runner call each helper with no arguments and report six spurious
// errors.
//
// The simulator's Application.Storage is REAL and survives between runs of
// the same app, and test order is not guaranteed. So every test that
// touches Storage calls resetStorage() as its FIRST statement, not its
// last — a failing assertion throws, so cleanup at the end of a test never
// runs and would leave the next test reading someone else's state.
(:test)
module TestSupport {

    // Resets Properties too, despite the name: serverUrl/enrollCode are
    // just as much cross-test state as anything in Storage, and a test
    // that cleaned them up at its own end would lose that cleanup the
    // moment an assertion above it failed. Properties has no
    // deleteValue(), so "" — the value properties.xml ships — is the
    // cleared state.
    function resetStorage() as Void {
        Properties.setValue("serverUrl", "");
        Properties.setValue("enrollCode", "");
        Storage.deleteValue(TrobarStorageKeys.DEVICE_TOKEN);
        Storage.deleteValue(TrobarStorageKeys.DEVICE_ID);
        Storage.deleteValue(TrobarStorageKeys.DEVICE_NAME);
        Storage.deleteValue(TrobarStorageKeys.LAST_PAIRING_STATUS);
        Storage.deleteValue(TrobarStorageKeys.CONTENT_MAP);
        Storage.deleteValue(TrobarStorageKeys.PLAY_ORDER);
        Storage.deleteValue(TrobarStorageKeys.LAST_SYNC_STATUS);
        Storage.deleteValue(TrobarStorageKeys.LAST_SYNC_AT);
    }

    // A /api/device/changes entry, in the wire shape the server actually
    // sends (trobar-server app/sync_state.py get_changes): track_id plus
    // the server-computed on-device path.
    function entry(trackId as Lang.Number, relativePath as Lang.String) as Lang.Dictionary {
        return {"track_id" => trackId, "relative_path" => relativePath};
    }

    // Seeds CONTENT_MAP as though each of these track ids had downloaded
    // successfully. The content id's actual value is opaque to everything
    // under test here — only its presence matters — so the track id doubles
    // as one.
    function seedContentMap(trackIds as Lang.Array) as Void {
        var map = {} as Lang.Dictionary;
        for (var i = 0; i < trackIds.size(); i++) {
            var id = trackIds[i] as Lang.Number;
            map[id.toString()] = id;
        }
        Storage.setValue(TrobarStorageKeys.CONTENT_MAP, map as Storage.ValueType);
    }

    // Storage.setValue's ValueType is a poly type that includes null, and
    // an array literal cast straight to it fails to type-check under -l 3
    // ("container assignment on a poly type containing null"). Building the
    // array as a Lang.Array first and casting the finished value is what
    // TrobarSyncDelegate already does for the same reason.
    function seedPlayOrder(trackIds as Lang.Array) as Void {
        var order = [] as Lang.Array;
        for (var i = 0; i < trackIds.size(); i++) {
            order.add(trackIds[i] as Lang.Object);
        }
        Storage.setValue(TrobarStorageKeys.PLAY_ORDER, order as Storage.ValueType);
    }

    // An .m3u8 body in the server's exact format — #EXTM3U, the Trobar
    // marker, #PLAYLIST:, and an #EXTINF: before every path, joined with
    // "\n" and trailing-newline-terminated (_device_playlists in
    // trobar-server). Tests that need to exercise CRLF or other shapes
    // build their content by hand instead.
    function m3u(title as Lang.String, paths as Lang.Array) as Lang.String {
        var out = "#EXTM3U\n# Generated by Trobar\n#PLAYLIST:" + title + "\n";
        for (var i = 0; i < paths.size(); i++) {
            out = out + "#EXTINF:213,Some Artist - Some Title\n" + (paths[i] as Lang.String) + "\n";
        }
        return out;
    }

    // Turns a PLAY_ORDER array into a comparable string, so a whole
    // expected ordering is one assertion with a readable failure rather
    // than a size check plus N index checks.
    function joinNumbers(values as Lang.Array) as Lang.String {
        var out = "";
        for (var i = 0; i < values.size(); i++) {
            if (i > 0) {
                out = out + ",";
            }
            out = out + (values[i] as Lang.Number).toString();
        }
        return out;
    }
}
