// SPDX-FileCopyrightText: 2026 missing-foss
// SPDX-License-Identifier: GPL-3.0-or-later
using Toybox.Test;
using Toybox.Lang;
using Toybox.Application.Storage;
using Toybox.Application.Properties;

// TrobarSyncDelegate's pure helpers: .m3u8 parsing, play-order
// computation, and the duck-typed content-id extraction. None of these
// touch the network — the callback-chained download/ack sequencing around
// them does, and is deliberately not covered here (it needs a real server
// and a real device; trobar-garmin#20 is the standing reminder that the
// watch's own sync UI can't be trusted to report it either way).
//
// Constructing a SyncDelegate outside a sync is fine: initialize() only
// chains to the parent, and every helper below reads its inputs from
// arguments or Storage.

// Stands in for whatever Communications.makeWebRequest hands back for an
// audio download. The real shape is unknown — TrobarApi.mc explains why
// only a real device can settle it — so what's pinned here is our own
// contract: _idFromHandle returns getId()'s value when the object has one.
(:test)
class FakeContentHandle {
    function initialize() {
    }

    function getId() as Lang.Object {
        return 4242;
    }
}

(:test)
function testStartsWithHash(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();
    Test.assert(d._startsWithHash("#EXTM3U"));
    Test.assert(d._startsWithHash("# Generated by Trobar"));
    Test.assert(!d._startsWithHash("Some Artist/Some Album/01 - Title.mp3"));
    // substring(0,1) on an empty string returns null, not "" — the null
    // guard in _startsWithHash is what stops that becoming a crash.
    Test.assert(!d._startsWithHash(""));
    return true;
}

(:test)
function testStripCR(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();
    Test.assertEqual(d._stripCR("A/B/01.mp3\r") as Lang.Object, "A/B/01.mp3");
    Test.assertEqual(d._stripCR("A/B/01.mp3") as Lang.Object, "A/B/01.mp3");
    Test.assertEqual(d._stripCR("") as Lang.Object, "");
    Test.assertEqual(d._stripCR("\r") as Lang.Object, "");
    return true;
}

(:test)
function testSplitLines(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();

    // The server always terminates its .m3u8 bodies with a newline, so the
    // trailing-empty-segment case is the normal one, not an edge case.
    var lines = d._splitLines("one\ntwo\n");
    Test.assertEqual(lines.size() as Lang.Object, 2);
    Test.assertEqual(lines[0] as Lang.Object, "one");
    Test.assertEqual(lines[1] as Lang.Object, "two");

    var unterminated = d._splitLines("one\ntwo");
    Test.assertEqual(unterminated.size() as Lang.Object, 2);
    Test.assertEqual(unterminated[1] as Lang.Object, "two");

    // Blank lines are preserved here and skipped later by
    // _orderFromPlaylist, rather than being dropped at the split.
    var blanks = d._splitLines("one\n\ntwo\n");
    Test.assertEqual(blanks.size() as Lang.Object, 3);
    Test.assertEqual(blanks[1] as Lang.Object, "");

    Test.assertEqual(d._splitLines("").size() as Lang.Object, 0);
    Test.assertEqual(d._splitLines("solo").size() as Lang.Object, 1);
    return true;
}

(:test)
function testOrderFromPlaylistFollowsFileOrder(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();
    // Entries deliberately in a different order from the playlist: the
    // .m3u8 is the only place track ordering is ever explicit.
    var entries = [
        TestSupport.entry(11, "Artist/Album/01 - First.mp3"),
        TestSupport.entry(22, "Artist/Album/02 - Second.mp3"),
        TestSupport.entry(33, "Artist/Album/03 - Third.mp3"),
    ] as Lang.Array;
    var content = TestSupport.m3u("Evening", [
        "Artist/Album/03 - Third.mp3",
        "Artist/Album/01 - First.mp3",
    ] as Lang.Array);

    var order = d._orderFromPlaylist(content, entries);
    Test.assertEqual(TestSupport.joinNumbers(order) as Lang.Object, "33,11");
    return true;
}

(:test)
function testOrderFromPlaylistIgnoresUnknownPaths(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();
    var entries = [TestSupport.entry(11, "Artist/Album/01 - First.mp3")] as Lang.Array;
    // A path the device isn't getting (excluded, or removed since the
    // playlist was written) must be skipped, not turn into a null entry.
    var content = TestSupport.m3u("Evening", [
        "Artist/Album/99 - Not Assigned.mp3",
        "Artist/Album/01 - First.mp3",
    ] as Lang.Array);

    var order = d._orderFromPlaylist(content, entries);
    Test.assertEqual(TestSupport.joinNumbers(order) as Lang.Object, "11");
    return true;
}

(:test)
function testOrderFromPlaylistSkipsCommentsAndBlanks(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();
    var entries = [TestSupport.entry(11, "Artist/Album/01 - First.mp3")] as Lang.Array;
    var content = "#EXTM3U\n# Generated by Trobar\n#PLAYLIST:Evening\n\n" +
        "#EXTINF:213,Some Artist - Some Title\nArtist/Album/01 - First.mp3\n";

    var order = d._orderFromPlaylist(content, entries);
    // One id, not four — every # line and the blank must be skipped, and
    // none of them may match a path.
    Test.assertEqual(TestSupport.joinNumbers(order) as Lang.Object, "11");
    return true;
}

(:test)
function testOrderFromPlaylistToleratesCRLF(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();
    var entries = [
        TestSupport.entry(11, "Artist/Album/01 - First.mp3"),
        TestSupport.entry(22, "Artist/Album/02 - Second.mp3"),
    ] as Lang.Array;
    // trobar-server joins with "\n" and never emits CRLF, so _stripCR is
    // defensive only. Pinned anyway: a hand-edited or re-saved playlist is
    // exactly the kind of thing that would arrive this way, and without
    // the strip every path would silently fail to match.
    var content = "#EXTM3U\r\nArtist/Album/02 - Second.mp3\r\nArtist/Album/01 - First.mp3\r\n";

    var order = d._orderFromPlaylist(content, entries);
    Test.assertEqual(TestSupport.joinNumbers(order) as Lang.Object, "22,11");
    return true;
}

(:test)
function testComputePlayOrderPlaylistFirstThenSortedRemainder(logger as Test.Logger) as Lang.Boolean {
    TestSupport.resetStorage();
    var d = new TrobarSyncDelegate();
    d._toDownload = [
        TestSupport.entry(3, "Beta/Album/01 - B.mp3"),
        TestSupport.entry(1, "Alpha/Album/02 - Second.mp3"),
    ] as Lang.Array;
    d._downloaded = [TestSupport.entry(2, "Alpha/Album/01 - First.mp3")] as Lang.Array;
    d._playlists = [
        {"content" => TestSupport.m3u("Evening", ["Alpha/Album/02 - Second.mp3"] as Lang.Array)},
    ] as Lang.Array;
    TestSupport.seedContentMap([1, 2, 3] as Lang.Array);

    d._computePlayOrder();

    // The playlist's track leads; everything else follows in relative_path
    // order, which is what reproduces album order (the server zero-pads
    // track numbers precisely so a lexicographic sort is correct).
    var order = Storage.getValue(TrobarStorageKeys.PLAY_ORDER) as Lang.Array;
    Test.assertEqual(TestSupport.joinNumbers(order) as Lang.Object, "1,2,3");
    return true;
}

(:test)
function testComputePlayOrderDedupesAcrossPlaylists(logger as Test.Logger) as Lang.Boolean {
    TestSupport.resetStorage();
    var d = new TrobarSyncDelegate();
    d._toDownload = [
        TestSupport.entry(1, "Alpha/Album/01 - One.mp3"),
        TestSupport.entry(2, "Alpha/Album/02 - Two.mp3"),
        TestSupport.entry(3, "Alpha/Album/03 - Three.mp3"),
    ] as Lang.Array;
    d._downloaded = [] as Lang.Array;
    // Track 2 is in both playlists. PLAY_ORDER is one flat queue, so it
    // must appear once — at the position the first playlist gave it.
    d._playlists = [
        {"content" => TestSupport.m3u("First", [
            "Alpha/Album/02 - Two.mp3", "Alpha/Album/01 - One.mp3",
        ] as Lang.Array)},
        {"content" => TestSupport.m3u("Second", [
            "Alpha/Album/02 - Two.mp3", "Alpha/Album/03 - Three.mp3",
        ] as Lang.Array)},
    ] as Lang.Array;
    TestSupport.seedContentMap([1, 2, 3] as Lang.Array);

    d._computePlayOrder();

    var order = Storage.getValue(TrobarStorageKeys.PLAY_ORDER) as Lang.Array;
    Test.assertEqual(TestSupport.joinNumbers(order) as Lang.Object, "2,1,3");
    return true;
}

(:test)
function testComputePlayOrderDropsTracksThatFailedToDownload(logger as Test.Logger) as Lang.Boolean {
    TestSupport.resetStorage();
    var d = new TrobarSyncDelegate();
    d._toDownload = [
        TestSupport.entry(1, "Alpha/Album/01 - One.mp3"),
        TestSupport.entry(2, "Alpha/Album/02 - Two.mp3"),
    ] as Lang.Array;
    d._downloaded = [] as Lang.Array;
    d._playlists = [
        {"content" => TestSupport.m3u("Both", [
            "Alpha/Album/01 - One.mp3", "Alpha/Album/02 - Two.mp3",
        ] as Lang.Array)},
    ] as Lang.Array;
    // Only track 1 made it into the content cache. Leaving 2 in PLAY_ORDER
    // would stop playback dead at that point — TrobarContentIterator
    // signals end-of-content with null, so a gap reads as "the end".
    TestSupport.seedContentMap([1] as Lang.Array);

    d._computePlayOrder();

    var order = Storage.getValue(TrobarStorageKeys.PLAY_ORDER) as Lang.Array;
    Test.assertEqual(TestSupport.joinNumbers(order) as Lang.Object, "1");
    return true;
}

(:test)
function testComputePlayOrderWithNoContentMapIsEmpty(logger as Test.Logger) as Lang.Boolean {
    TestSupport.resetStorage();
    var d = new TrobarSyncDelegate();
    d._toDownload = [TestSupport.entry(1, "Alpha/Album/01 - One.mp3")] as Lang.Array;
    d._downloaded = [] as Lang.Array;
    d._playlists = [] as Lang.Array;
    // No CONTENT_MAP at all — a first sync where every download failed.

    d._computePlayOrder();

    var order = Storage.getValue(TrobarStorageKeys.PLAY_ORDER) as Lang.Array;
    Test.assertEqual(order.size() as Lang.Object, 0);
    return true;
}

(:test)
function testSortEntriesByRelativePath(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();
    var entries = [
        TestSupport.entry(4, "Artist/Album/CD2-01 - D.mp3"),
        TestSupport.entry(2, "Artist/Album/02 - B.mp3"),
        TestSupport.entry(3, "Artist/Album/CD1-01 - C.mp3"),
        TestSupport.entry(1, "Artist/Album/01 - A.mp3"),
    ] as Lang.Array;

    d._sortEntriesByRelativePath(entries);

    var ids = [] as Lang.Array;
    for (var i = 0; i < entries.size(); i++) {
        ids.add((entries[i] as Lang.Dictionary)["track_id"] as Lang.Object);
    }
    // Zero-padded track numbers and the CDn- prefix are what make a plain
    // lexicographic sort produce correct album order.
    Test.assertEqual(TestSupport.joinNumbers(ids) as Lang.Object, "1,2,3,4");
    return true;
}

(:test)
function testRecordSyncOutcome(logger as Test.Logger) as Lang.Boolean {
    TestSupport.resetStorage();
    var d = new TrobarSyncDelegate();

    d._recordSyncOutcome("network");
    Test.assertEqual(
        Storage.getValue(TrobarStorageKeys.LAST_SYNC_STATUS) as Lang.Object, "network");
    Test.assert(Storage.getValue(TrobarStorageKeys.LAST_SYNC_AT) != null);

    // A successful sync must CLEAR the reason, not overwrite it with
    // something falsy — a stale "network" left behind would describe the
    // run before this one.
    d._recordSyncOutcome(null);
    Test.assert(Storage.getValue(TrobarStorageKeys.LAST_SYNC_STATUS) == null);
    Test.assert(Storage.getValue(TrobarStorageKeys.LAST_SYNC_AT) != null);
    return true;
}

(:test)
function testPairingFailureRecordsTheOutcome(logger as Test.Logger) as Lang.Boolean {
    TestSupport.resetStorage();
    Storage.setValue(TrobarStorageKeys.LAST_SYNC_STATUS, "from-a-previous-run");
    var d = new TrobarSyncDelegate();

    // The most-travelled failure path: onStartSync always goes through
    // redeemIfNeeded first, so this is what a watch with a bad enrollment
    // code hits every time. It must not leave the previous run's status
    // behind.
    d._onPairingDone(false, "invalid_code");

    Test.assertEqual(
        Storage.getValue(TrobarStorageKeys.LAST_SYNC_STATUS) as Lang.Object, "invalid_code");
    return true;
}

(:test)
function testComparePaths(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();

    Test.assert(d._comparePaths("Alpha", "Beta") < 0);
    Test.assert(d._comparePaths("Beta", "Alpha") > 0);
    Test.assertEqual(d._comparePaths("Alpha", "Alpha") as Lang.Object, 0);

    // A prefix sorts before the longer string it prefixes — the length
    // fallback, reached only when every shared character matches.
    Test.assert(d._comparePaths("Artist/Album/01", "Artist/Album/01 - Title.mp3") < 0);
    Test.assertEqual(d._comparePaths("", "") as Lang.Object, 0);
    Test.assert(d._comparePaths("", "anything") < 0);

    // Zero-padded track numbers are the whole reason a lexicographic sort
    // reproduces album order: unpadded, "10" would sort before "2".
    Test.assert(d._comparePaths("02 - Second.mp3", "10 - Tenth.mp3") < 0);
    Test.assert(d._comparePaths("CD1-01 - A.mp3", "CD2-01 - B.mp3") < 0);
    return true;
}

(:test)
function testExtractContentIdRejectsFailures(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();
    Test.assert(d._extractContentId(404, null) == null);
    Test.assert(d._extractContentId(200, null) == null);
    // A 200 that handed back something with no id is a failed download as
    // far as this app is concerned, not a track to record.
    Test.assert(d._extractContentId(200, "not a content handle") == null);
    return true;
}

(:test)
function testExtractContentIdReadsASuccessfulDownload(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();
    // The branch that decides whether a downloaded track ever reaches
    // CONTENT_MAP — and so whether it is playable at all. The declared
    // parameter type is makeWebRequest's own fixed union, which can't name
    // whatever the audio responseType really hands back (see TrobarApi),
    // so the cast is how a stand-in gets through the type checker; the
    // runtime `has :getId` check is the real arbiter either way.
    var handle = new FakeContentHandle();
    Test.assertEqual(d._extractContentId(200, handle as Lang.String) as Lang.Object, 4242);
    return true;
}

(:test)
function testIdFromHandleReadsGetId(logger as Test.Logger) as Lang.Boolean {
    var d = new TrobarSyncDelegate();
    var handle = new FakeContentHandle();
    Test.assertEqual(d._idFromHandle(handle as Lang.Object) as Lang.Object, 4242);
    // The `has :getId` guard is the whole point: anything else yields null
    // rather than throwing on a missing symbol.
    Test.assert(d._idFromHandle("a string" as Lang.Object) == null);
    Test.assert(d._idFromHandle(17 as Lang.Object) == null);
    return true;
}

(:test)
function testIsSyncNeededWhenPaired(logger as Test.Logger) as Lang.Boolean {
    TestSupport.resetStorage();
    var d = new TrobarSyncDelegate();
    Storage.setValue(TrobarStorageKeys.DEVICE_TOKEN, "a-token");
    // Paired is enough on its own — the app deliberately syncs on every
    // opportunity rather than trying to guess that nothing changed.
    Test.assert(d.isSyncNeeded());
    return true;
}

(:test)
function testIsSyncNeededBeforePairing(logger as Test.Logger) as Lang.Boolean {
    TestSupport.resetStorage();
    var d = new TrobarSyncDelegate();

    // resetStorage() has already cleared both properties.
    Test.assert(!d.isSyncNeeded());

    // A server URL with no code (or the reverse) can't redeem anything, so
    // waking WiFi for it would burn battery for a guaranteed failure.
    Properties.setValue("serverUrl", "https://trobar.example.com");
    Test.assert(!d.isSyncNeeded());

    Properties.setValue("enrollCode", "ABC123");
    Test.assert(d.isSyncNeeded());
    return true;
}

(:test)
function testIsSyncNeededIgnoresAnUnusableUrl(logger as Test.Logger) as Lang.Boolean {
    TestSupport.resetStorage();
    var d = new TrobarSyncDelegate();

    // Both fields filled in, but the URL has no scheme, so no request could
    // succeed — waking WiFi for it would spend battery on a guaranteed
    // failure (trobar-garmin#43).
    Properties.setValue("serverUrl", "trobar.example.com");
    Properties.setValue("enrollCode", "ABC123");
    Test.assert(!d.isSyncNeeded());

    Properties.setValue("serverUrl", "https://trobar.example.com");
    Test.assert(d.isSyncNeeded());
    return true;
}
